package com.mosstis.kofest.core.ui.strings

internal val EnStrings = KoFestStrings(
    meta = KoFestStrings.Meta(name = "English", dateFormat = "MMM d"),
    app = KoFestStrings.App(name = "KoFest", tagline = "Every festival in Korea, in one place"),
    nav = KoFestStrings.Nav(home = "Home", list = "List", calendar = "Calendar", saved = "MY"),
    action = KoFestStrings.Action(
        search = "Search",
        back = "Back",
        retry = "Try again",
        seeAll = "All {count}",
        share = "Share",
        call = "Call",
        save = "Save",
        saved = "Saved",
        clearFilters = "Clear filters",
    ),
    home = KoFestStrings.Home(
        ongoingTitle = "Happening today",
        ongoingSub = "지금 열리는 축제",
        weekendTitleThis = "This weekend",
        weekendTitleNext = "Next weekend",
        weekendSub = "{start} – {end}",
        regionTitle = "By region",
        regionSub = "지역으로 찾기",
        regionAll = "Browse all festivals",
        bannerThisWeek = "This week",
        bannerEndsSoon = "Ends soon",
        bannerFeatured = "Featured festival",
    ),
    list = KoFestStrings.ListStrings(
        title = "Browse",
        titleRegion = "Festivals in {region}",
        count = "{count} festivals",
        monthCount = "{month} · {count} festivals",
    ),
    filter = KoFestStrings.Filter(
        regionAll = "Nationwide",
        thisMonth = "This month",
        ongoing = "Happening now",
        hasImage = "With photo",
    ),
    state = KoFestStrings.State(
        ongoing = "Now on",
        lastDay = "Last day",
        upcoming = "In {days} days",
        tomorrow = "Tomorrow",
        today = "Starts today",
        ended = "Ended",
        startsIn = "Starts in {days} days",
        endsToday = "Last day",
    ),
    intro = KoFestStrings.Intro(
        splashHeadline = "한국은 1년 내내\n어딘가에서\n축제가 열립니다",
        splashSub = "Festivals happen somewhere in Korea\nevery day of the year.",
        dataSource = "Data from Korea Tourism Organization",
        langKicker = "Choose your language",
        langTitle = "어떤 언어로\n보시겠어요?",
        langDesc = "언어에 따라 볼 수 있는 축제 수가 다릅니다.\nThe number of festivals differs by language.",
        langKoLabel = "모든 축제를 볼 수 있어요",
        langEnLabel = "Translated listings only",
        langNote = "한국관광공사가 일부 축제만 번역해서 제공합니다.\n" +
            "The Korea Tourism Organization translates only part of its listings.",
        start = "시작하기 · Start",
        changeAnytime = "나중에 바꿀 수 있어요 · Change anytime",
    ),
    calendar = KoFestStrings.Calendar(
        title = "Calendar",
        monthCount = "{count} festivals",
        prevMonth = "Previous month",
        nextMonth = "Next month",
        selected = "{weekday}, {month} {day}",
        dayCount = "{count} festivals",
        firstDay = "Opens",
        lastDay = "Last day",
        ongoing = "Now on",
        noneToday = "No festivals on this day",
        noneHint = "The next one is on {date}.",
        noneInLang = "Korean listings show {count} on this day.",
        today = "Today",
    ),
    my = KoFestStrings.My(
        title = "MY",
        savedCount = "Saved",
        upcomingCount = "Coming up",
        savedList = "Saved festivals",
        savedOrder = "Soonest first",
        pastToggle = "{count} past",
        expand = "Show",
        collapse = "Hide",
        unsave = "Remove",
        settings = "Settings",
        language = "Language",
        notify = "Festival reminders",
        notifyOn = "On",
        notifyOff = "Off",
        notifySoon = "Coming soon",
        notifyAsk = "Want a reminder before this festival starts?",
        about = "About",
        dataSource = "Data source",
        dataSourceVal = "Korea Tourism Organization",
        privacy = "Privacy policy",
        feedback = "Send feedback",
        version = "Version",
        localOnly = "Saved festivals stay on this device.\nThey're gone if you delete the app.",
        emptyTitle = "Nothing saved yet",
        emptyHint = "Tap the heart on any festival\nand it'll show up here.",
        emptyCta = "Browse festivals",
        terms = "Terms & policies",
        tos = "Terms of service",
        license = "Open source licences",
        copyright = "Data source & copyright",
        clearCache = "Free up space",
        clearCacheAsk = "Clear {size} of cached images?\nYour saved festivals stay.",
        versionLatest = "Up to date",
        versionUpdate = "Update available",
    ),
    detail = KoFestStrings.Detail(
        overview = "About",
        info = "Details",
        program = "Programme",
        hosts = "Organisers",
        photos = "Photos",
        location = "Location",
        nearby = "Festivals nearby",
        nearbyRange = "Within 50 km",
        place = "Where",
        playTime = "Hours",
        fee = "Admission",
        discount = "Discounts",
        spendTime = "Time needed",
        ageLimit = "Age",
        booking = "Booking",
        placeInfo = "Venue notes",
        subEvent = "Side events",
        grade = "Rating",
        days = "{days} days",
        oneDay = "One day",
        more = "Read more",
        less = "Show less",
        directions = "Directions",
        openInMaps = "Open in maps",
        homepage = "Website",
        photoCount = "{current} / {total}",
        noOverview = "No description has been published for this festival yet.",
        noOverviewSoon = "We're still gathering details. Check back in a few days.",
    ),
    language = KoFestStrings.Language(
        current = "English",
        switch = "한국어로 보기",
        noticeTitle = "You're seeing English listings",
        notice = "{en} festivals are listed in English. {ko} are listed in Korean.",
        noticeWhy = "The Korea Tourism Organization translates only part of its listings.",
        detailNotice = "Korean listings often have more detail for this festival.",
        moreHere = "Switching to Korean shows {count} festivals here.",
    ),
    empty = KoFestStrings.Empty(
        noResult = "No festivals match these filters",
        noResultRegion = "No festivals in {region} for these dates",
        noResultHint = "Try changing the filters.",
        noSaved = "Nothing saved yet",
        noSavedHint = "Save a festival and it'll show up here.",
        noPhotos = "No photos available",
    ),
    error = KoFestStrings.ErrorStrings(
        offline = "Showing saved listings. Last updated {time}.",
        loadFailed = "Couldn't load festivals",
        loadFailedHint = "Check your connection and try again.",
        notFound = "This festival isn't available",
    ),
    loading = KoFestStrings.Loading(default = "Loading"),
    region = mapOf(
        "11" to "Seoul", "26" to "Busan", "27" to "Daegu", "28" to "Incheon",
        "29" to "Gwangju", "30" to "Daejeon", "31" to "Ulsan", "36" to "Sejong",
        "41" to "Gyeonggi", "43" to "Chungbuk", "44" to "Chungnam", "46" to "Jeonnam",
        "47" to "Gyeongbuk", "48" to "Gyeongnam", "50" to "Jeju", "51" to "Gangwon",
        "52" to "Jeonbuk",
    ),
)
