package com.mosstis.kofest.core.ui.strings

internal val KoStrings = KoFestStrings(
    meta = KoFestStrings.Meta(name = "한국어", dateFormat = "MM.dd"),
    app = KoFestStrings.App(name = "KoFest", tagline = "한국의 축제를 한눈에"),
    nav = KoFestStrings.Nav(home = "홈", list = "목록", calendar = "달력", saved = "MY"),
    action = KoFestStrings.Action(
        search = "검색",
        back = "뒤로",
        retry = "다시 시도",
        seeAll = "전체 {count}",
        share = "공유",
        call = "전화",
        save = "저장",
        saved = "저장됨",
        clearFilters = "필터 해제",
    ),
    home = KoFestStrings.Home(
        ongoingTitle = "지금 열리는 축제",
        ongoingSub = "Happening today",
        weekendTitleThis = "이번 주말",
        weekendTitleNext = "다음 주말",
        weekendSub = "{start} – {end}",
        regionTitle = "지역으로 찾기",
        regionSub = "By region",
        regionAll = "전국 축제 모두 보기",
        bannerThisWeek = "This week",
        bannerEndsSoon = "Ends soon",
        bannerFeatured = "문화관광축제",
    ),
    list = KoFestStrings.ListStrings(
        title = "둘러보기",
        titleRegion = "{region}의 축제",
        count = "축제 {count}",
        monthCount = "{month} · 축제 {count}",
    ),
    filter = KoFestStrings.Filter(
        regionAll = "전국",
        thisMonth = "이번 달",
        ongoing = "진행중",
        hasImage = "사진 있는 것",
    ),
    state = KoFestStrings.State(
        ongoing = "진행중",
        lastDay = "오늘 마지막",
        upcoming = "{days}일 뒤",
        tomorrow = "내일",
        today = "오늘 시작",
        ended = "종료",
        startsIn = "{days}일 뒤 시작",
        endsToday = "오늘 마지막",
    ),
    intro = KoFestStrings.Intro(
        splashHeadline = "한국은 1년 내내\n어딘가에서\n축제가 열립니다",
        splashSub = "Festivals happen somewhere in Korea\nevery day of the year.",
        dataSource = "Data from Korea Tourism Organization",
        langKicker = "Choose your language",
        langTitle = "어떤 언어로\n보시겠어요?",
        langDesc = "언어에 따라 볼 수 있는 축제 수가 다릅니다.\nThe number of festivals differs by language.",
        langKoLabel = "모든 축제를 볼 수 있어요",
        langEnLabel = "Translated listings only",
        langNote = "한국관광공사가 일부 축제만 번역해서 제공합니다.\n" +
            "The Korea Tourism Organization translates only part of its listings.",
        start = "시작하기 · Start",
        changeAnytime = "나중에 바꿀 수 있어요 · Change anytime",
    ),
    calendar = KoFestStrings.Calendar(
        title = "달력",
        monthCount = "축제 {count}",
        prevMonth = "이전 달",
        nextMonth = "다음 달",
        selected = "{month}월 {day}일 {weekday}",
        dayCount = "축제 {count}",
        firstDay = "첫날",
        lastDay = "마지막 날",
        ongoing = "진행중",
        noneToday = "이날 열리는 축제가 없습니다",
        noneHint = "가장 가까운 축제는 {date} 입니다.",
        noneInLang = "한국어로 보면 이날 {count}건이 있습니다.",
        today = "오늘",
    ),
    my = KoFestStrings.My(
        title = "MY",
        savedCount = "저장한 축제",
        upcomingCount = "다가오는 축제",
        savedList = "저장한 축제",
        savedOrder = "시작일이 가까운 순",
        pastToggle = "지난 축제 {count}",
        expand = "펼치기",
        collapse = "접기",
        unsave = "저장 해제",
        settings = "설정",
        language = "언어",
        notify = "축제 시작 알림",
        notifyOn = "켜짐",
        notifyOff = "꺼짐",
        notifySoon = "준비 중입니다",
        notifyAsk = "이 축제가 시작하기 전에 알려드릴까요?",
        about = "앱 정보",
        dataSource = "데이터 출처",
        dataSourceVal = "한국관광공사",
        privacy = "개인정보 처리방침",
        feedback = "의견 보내기",
        version = "버전",
        localOnly = "저장한 축제는 이 기기에만 보관됩니다.\n앱을 지우면 함께 사라집니다.",
        emptyTitle = "저장한 축제가 없습니다",
        emptyHint = "축제 상세에서 하트를 누르면\n여기에 모입니다.",
        emptyCta = "축제 둘러보기",
        terms = "약관 · 정책",
        tos = "서비스 이용약관",
        license = "오픈소스 라이선스",
        copyright = "데이터 출처 · 저작권",
        clearCache = "저장 공간 비우기",
        clearCacheAsk = "이미지 캐시 {size} 를 지울까요?\n저장한 축제는 지워지지 않습니다.",
        versionLatest = "최신",
        versionUpdate = "업데이트 있음",
    ),
    detail = KoFestStrings.Detail(
        overview = "축제 소개",
        info = "안내",
        program = "프로그램",
        hosts = "주최 · 주관",
        photos = "사진",
        location = "위치",
        nearby = "주변 축제",
        nearbyRange = "50km 이내",
        place = "장소",
        playTime = "시간",
        fee = "요금",
        discount = "할인",
        spendTime = "소요시간",
        ageLimit = "연령",
        booking = "예매",
        placeInfo = "장소 안내",
        subEvent = "부대행사",
        grade = "축제 등급",
        days = "{days}일간",
        oneDay = "하루",
        more = "더 보기",
        less = "접기",
        directions = "길찾기",
        openInMaps = "지도 앱에서 열기",
        homepage = "홈페이지",
        photoCount = "{current} / {total}",
        noOverview = "이 축제는 아직 소개 정보가 등록되지 않았습니다.",
        noOverviewSoon = "소개 정보를 준비하고 있습니다. 며칠 뒤 다시 확인해 주세요.",
    ),
    language = KoFestStrings.Language(
        current = "한국어",
        switch = "Switch to English",
        noticeTitle = "지금은 한국어로 보고 있어요",
        notice = "한국어로 {ko}건, 영어로 {en}건을 볼 수 있습니다.",
        noticeWhy = "한국관광공사가 일부 축제만 번역해서 제공합니다.",
        detailNotice = "한국어로 보면 이 축제의 소개 정보가 있을 수 있습니다.",
        moreHere = "영어로 보면 이곳에 {count}건이 있습니다.",
    ),
    empty = KoFestStrings.Empty(
        noResult = "조건에 맞는 축제가 없습니다",
        noResultRegion = "{region}에 이 기간 열리는 축제가 없습니다",
        noResultHint = "필터를 바꾸면 다른 축제를 볼 수 있어요.",
        noSaved = "저장한 축제가 없습니다",
        noSavedHint = "마음에 드는 축제를 저장해두면 여기서 볼 수 있어요.",
        noPhotos = "등록된 사진이 없습니다",
    ),
    error = KoFestStrings.ErrorStrings(
        offline = "저장된 정보를 보고 있어요. 마지막 갱신 {time}",
        loadFailed = "축제 정보를 불러오지 못했습니다",
        loadFailedHint = "잠시 뒤 다시 시도해 주세요.",
        notFound = "이 축제를 찾을 수 없습니다",
    ),
    loading = KoFestStrings.Loading(default = "불러오는 중"),
    region = mapOf(
        "11" to "서울", "26" to "부산", "27" to "대구", "28" to "인천",
        "29" to "광주", "30" to "대전", "31" to "울산", "36" to "세종",
        "41" to "경기", "43" to "충북", "44" to "충남", "46" to "전남",
        "47" to "경북", "48" to "경남", "50" to "제주", "51" to "강원",
        "52" to "전북",
    ),
)
