package com.mosstis.kofest.core.ui.strings

internal val KoStrings = KoFestStrings(
    meta = KoFestStrings.Meta(name = "한국어", dateFormat = "MM.dd"),
    app = KoFestStrings.App(name = "KoFest", tagline = "한국의 축제를 한눈에"),
    nav = KoFestStrings.Nav(
        home = "홈",
        list = "목록",
        calendar = "달력",
        plan = "일정",
        story = "매거진",
        saved = "MY",
    ),
    action = KoFestStrings.Action(
        search = "검색",
        back = "뒤로",
        close = "닫기",
        retry = "다시 시도",
        seeAll = "전체 {count}",
        share = "공유",
        call = "전화",
        save = "저장",
        saved = "저장됨",
        clearFilters = "필터 해제",
    ),
    home = KoFestStrings.Home(
        ongoingTitle = "지금 열리는 축제",
        ongoingSub = "Happening today",
        picksTitle = "가볼 만한 여행지",
        picksSub = "오늘의 추천",
        picksAll = "전체 보기",
        regionTitle = "지역으로 찾기",
        regionSub = "By region",
        regionAll = "전국 축제 모두 보기",
        bannerThisWeek = "This week",
        bannerEndsSoon = "Ends soon",
        bannerFeatured = "문화관광축제",
    ),
    list = KoFestStrings.ListStrings(
        title = "둘러보기",
        titleRegion = "{region}의 축제",
        count = "축제 {count}",
        monthCount = "{month} · 축제 {count}",
        tabFestival = "축제",
        tabPlace = "관광",
    ),
    filter = KoFestStrings.Filter(
        regionAll = "전국",
        thisMonth = "이번 달",
        ongoing = "진행중",
        hasImage = "사진 있는 것",
    ),
    state = KoFestStrings.State(
        ongoing = "진행중",
        lastDay = "오늘 마지막",
        upcoming = "{days}일 뒤",
        tomorrow = "내일",
        today = "오늘 시작",
        ended = "종료",
        startsIn = "{days}일 뒤 시작",
        endsToday = "오늘 마지막",
    ),
    intro = KoFestStrings.Intro(
        splashHeadline = "한국은 1년 내내\n어딘가에서\n축제가 열립니다",
        splashSub = "Festivals happen somewhere in Korea\nevery day of the year.",
        dataSource = "Data from Korea Tourism Organization",
        langKicker = "Choose your language",
        langTitle = "어떤 언어로\n보시겠어요?",
        langDesc = "언어에 따라 볼 수 있는 축제 수가 다릅니다.\nThe number of festivals differs by language.",
        langKoLabel = "모든 축제를 볼 수 있어요",
        langEnLabel = "Translated listings only",
        langNote = "한국관광공사가 일부 축제만 번역해서 제공합니다.\n" +
            "The Korea Tourism Organization translates only part of its listings.",
        start = "시작하기 · Start",
        changeAnytime = "나중에 바꿀 수 있어요 · Change anytime",
    ),
    calendar = KoFestStrings.Calendar(
        title = "달력",
        monthCount = "축제 {count}",
        prevMonth = "이전 달",
        nextMonth = "다음 달",
        selected = "{month}월 {day}일 {weekday}",
        dayCount = "축제 {count}",
        firstDay = "첫날",
        lastDay = "마지막 날",
        ongoing = "진행중",
        noneToday = "이날 열리는 축제가 없습니다",
        noneHint = "가장 가까운 축제는 {date} 입니다.",
        noneInLang = "한국어로 보면 이날 {count}건이 있습니다.",
        today = "오늘",
    ),
    my = KoFestStrings.My(
        title = "MY",
        trips = "내 일정",
        tripsEmpty = "저장한 일정이 없습니다",
        savedCount = "저장한 축제",
        upcomingCount = "다가오는 축제",
        savedList = "저장한 축제",
        savedOrder = "시작일이 가까운 순",
        pastToggle = "지난 축제 {count}",
        expand = "펼치기",
        collapse = "접기",
        unsave = "저장 해제",
        settings = "설정",
        language = "언어",
        notify = "축제 시작 알림",
        notifyOn = "켜짐",
        notifyOff = "꺼짐",
        notifySoon = "준비 중입니다",
        notifyAsk = "이 축제가 시작하기 전에 알려드릴까요?",
        about = "앱 정보",
        dataSource = "데이터 출처",
        dataSourceVal = "한국관광공사",
        privacy = "개인정보 처리방침",
        feedback = "의견 보내기",
        version = "버전",
        localOnly = "저장한 축제는 이 기기에만 보관됩니다.\n앱을 지우면 함께 사라집니다.",
        emptyTitle = "저장한 축제가 없습니다",
        emptyHint = "축제 상세에서 하트를 누르면\n여기에 모입니다.",
        emptyCta = "축제 둘러보기",
        terms = "약관 · 정책",
        tos = "서비스 이용약관",
        license = "오픈소스 라이선스",
        copyright = "데이터 출처 · 저작권",
        clearCache = "저장 공간 비우기",
        clearCacheAsk = "이미지 캐시 {size} 를 지울까요?\n저장한 축제는 지워지지 않습니다.",
        versionLatest = "최신",
        versionUpdate = "업데이트 있음",
    ),
    detail = KoFestStrings.Detail(
        overview = "축제 소개",
        info = "안내",
        program = "프로그램",
        hosts = "주최 · 주관",
        photos = "사진",
        location = "위치",
        nearby = "주변 축제",
        nearbyRange = "50km 이내",
        place = "장소",
        playTime = "시간",
        fee = "요금",
        discount = "할인",
        spendTime = "소요시간",
        ageLimit = "연령",
        booking = "예매",
        placeInfo = "장소 안내",
        subEvent = "부대행사",
        grade = "축제 등급",
        days = "{days}일간",
        oneDay = "하루",
        more = "더 보기",
        less = "접기",
        directions = "길찾기",
        openInMaps = "지도 앱에서 열기",
        homepage = "홈페이지",
        photoCount = "{current} / {total}",
        noOverview = "이 축제는 아직 소개 정보가 등록되지 않았습니다.",
        noOverviewSoon = "소개 정보를 준비하고 있습니다. 며칠 뒤 다시 확인해 주세요.",
    ),
    language = KoFestStrings.Language(
        current = "한국어",
        switch = "Switch to English",
        noticeTitle = "지금은 한국어로 보고 있어요",
        notice = "한국어로 {ko}건, 영어로 {en}건을 볼 수 있습니다.",
        noticeWhy = "한국관광공사가 일부 축제만 번역해서 제공합니다.",
        detailNotice = "한국어로 보면 이 축제의 소개 정보가 있을 수 있습니다.",
        moreHere = "영어로 보면 이곳에 {count}건이 있습니다.",
    ),
    empty = KoFestStrings.Empty(
        noResult = "조건에 맞는 축제가 없습니다",
        noResultRegion = "{region}에 이 기간 열리는 축제가 없습니다",
        noResultHint = "필터를 바꾸면 다른 축제를 볼 수 있어요.",
        noSaved = "저장한 축제가 없습니다",
        noSavedHint = "마음에 드는 축제를 저장해두면 여기서 볼 수 있어요.",
        noPhotos = "등록된 사진이 없습니다",
        searchNoResult = "'{query}' 검색 결과가 없습니다",
    ),
    error = KoFestStrings.ErrorStrings(
        offline = "저장된 정보를 보고 있어요. 마지막 갱신 {time}",
        loadFailed = "축제 정보를 불러오지 못했습니다",
        loadFailedHint = "잠시 뒤 다시 시도해 주세요.",
        notFound = "이 축제를 찾을 수 없습니다",
    ),
    loading = KoFestStrings.Loading(default = "불러오는 중"),
    place = KoFestStrings.PlaceStrings(
        title = "가볼 만한 곳",
        sub = "Places to visit",
        seeAll = "전체 보기",
        count = "관광지 {count}",
        filterType = "유형",
        type12 = "관광지",
        type14 = "문화시설",
        type28 = "레포츠",
        type38 = "쇼핑",
        type39 = "음식점",
        nearby = "주변 관광지",
        noResult = "조건에 맞는 곳이 없습니다",
        noOverview = "자세한 소개는 준비 중입니다",
        comingSoonRegion = "이 지역의 관광지는 준비 중입니다",
    ),
    theme = KoFestStrings.ThemeStrings(
        title = "지금 떠나기 좋은 곳",
        sub = "골라 담은 여행 코스",
        count = "{n}곳",
        open = "펼치기",
        close = "접기",
        kindFestival = "축제",
        kindPlace = "관광",
    ),
    story = KoFestStrings.StoryStrings(
        title = "매거진",
        sub = "Stories",
        pinned = "추천",
        empty = "아직 올라온 글이 없습니다",
        more = "다른 글",
        published = "{date}",
        updated = "{date} 수정",
    ),
    plan = KoFestStrings.PlanStrings(
        title = "자동 일정 짜기",
        lead = "지역과 날짜만 고르면 코스를 만들어 드립니다",
        where = "어디로",
        whenLabel = "언제",
        howLong = "며칠",
        how = "어떻게",
        build = "결과 보기",
        rebuild = "다시 짜기",
        pickAreaFirst = "지역을 먼저 골라주세요",
        nights0 = "당일",
        nights = "{n}박 {m}일",
        moodFestival = "축제 위주로",
        moodFestivalDesc = "그날 열리는 축제를 먼저 넣고, 근처를 채웁니다",
        moodEasy = "여유롭게",
        moodEasyDesc = "하루 세 곳. 한 동네 안에서만 움직입니다",
        moodMany = "많이 보기",
        moodManyDesc = "하루 다섯 곳. 이동이 조금 많습니다",
        resultTitle = "{area} {nights}",
        summary = "{range} · {mood} · {total}곳",
        withFestivals = "축제 {n}개 포함",
        day = "{n}일차",
        stay = "{n}분",
        walk = "도보 {n}분",
        transit = "대중교통",
        lunch = "점심",
        dinner = "저녁",
        festivalTag = "축제",
        noStops = "이날은 넣을 만한 곳을 찾지 못했습니다",
        thin = "이 지역은 아직 관광지 정보가 적습니다. 축제 위주로 짜였습니다.",
        distanceNote = "거리는 직선거리 기준입니다. 실제 경로와 다를 수 있습니다.",
        save = "내 일정에 담기",
        saved = "담았습니다",
        loading = listOf(
            "지도 펴는 중",
            "축제 일정 뒤지는 중",
            "가까운 순으로 줄 세우는 중",
            "발품은 저희가 팔게요",
            "점심 자리 비워두는 중",
            "동선 다듬는 중",
        ),
        loadingDone = "일정 완성",
    ),
    area = KoFestStrings.AreaStrings(
        seoul = "서울",
        gyeonggi = "경기·인천",
        gangwon = "강원",
        chungcheong = "충청",
        jeolla = "전라",
        gyeongsang = "경상",
        busan = "부산·울산",
        jeju = "제주",
    ),
    region = mapOf(
        "11" to "서울", "26" to "부산", "27" to "대구", "28" to "인천",
        "29" to "광주", "30" to "대전", "31" to "울산", "36" to "세종",
        "41" to "경기", "43" to "충북", "44" to "충남", "46" to "전남",
        "47" to "경북", "48" to "경남", "50" to "제주", "51" to "강원",
        "52" to "전북",
    ),
)
